# ── All countries with IANA timezone keys ──
# Format: ("Country", "IANA/timezone") or ("Country — Region", "IANA/timezone")

# NONE OF THIS IS VERIFIED, TAKE IT WITH A GRAIN OF SALT.

COUNTRIES = [
    ("Afghanistan", "Asia/Kabul"),
    ("Albania", "Europe/Tirane"),
    ("Algeria", "Africa/Algiers"),
    ("Andorra", "Europe/Andorra"),
    ("Angola", "Africa/Luanda"),
    ("Antigua & Barbuda", "America/Antigua"),
    ("Argentina", "America/Argentina/Buenos_Aires"),
    ("Armenia", "Asia/Yerevan"),
    ("Australia — East", "Australia/Sydney"),
    ("Australia — Central", "Australia/Adelaide"),
    ("Australia — West", "Australia/Perth"),
    ("Austria", "Europe/Vienna"),
    ("Azerbaijan", "Asia/Baku"),
    ("Bahamas", "America/Nassau"),
    ("Bahrain", "Asia/Bahrain"),
    ("Bangladesh", "Asia/Dhaka"),
    ("Barbados", "America/Barbados"),
    ("Belarus", "Europe/Minsk"),
    ("Belgium", "Europe/Brussels"),
    ("Belize", "America/Belize"),
    ("Benin", "Africa/Porto-Novo"),
    ("Bhutan", "Asia/Thimphu"),
    ("Bolivia", "America/La_Paz"),
    ("Bosnia & Herzegovina", "Europe/Sarajevo"),
    ("Botswana", "Africa/Gaborone"),
    ("Brazil — East", "America/Sao_Paulo"),
    ("Brazil — West", "America/Manaus"),
    ("Brunei", "Asia/Brunei"),
    ("Bulgaria", "Europe/Sofia"),
    ("Burkina Faso", "Africa/Ouagadougou"),
    ("Burundi", "Africa/Bujumbura"),
    ("Cabo Verde", "Atlantic/Cape_Verde"),
    ("Cambodia", "Asia/Phnom_Penh"),
    ("Cameroon", "Africa/Douala"),
    ("Canada — Eastern", "America/Toronto"),
    ("Canada — Central", "America/Winnipeg"),
    ("Canada — Mountain", "America/Edmonton"),
    ("Canada — Pacific", "America/Vancouver"),
    ("Central African Rep.", "Africa/Bangui"),
    ("Chad", "Africa/Ndjamena"),
    ("Chile", "America/Santiago"),
    ("China", "Asia/Shanghai"),
    ("Colombia", "America/Bogota"),
    ("Comoros", "Indian/Comoro"),
    ("Congo (Brazzaville)", "Africa/Brazzaville"),
    ("Congo (Kinshasa) — W", "Africa/Kinshasa"),
    ("Congo (Kinshasa) — E", "Africa/Lubumbashi"),
    ("Costa Rica", "America/Costa_Rica"),
    ("Côte d'Ivoire", "Africa/Abidjan"),
    ("Croatia", "Europe/Zagreb"),
    ("Cuba", "America/Havana"),
    ("Cyprus", "Asia/Nicosia"),
    ("Czech Republic", "Europe/Prague"),
    ("Denmark", "Europe/Copenhagen"),
    ("Djibouti", "Africa/Djibouti"),
    ("Dominica", "America/Dominica"),
    ("Dominican Republic", "America/Santo_Domingo"),
    ("Ecuador", "America/Guayaquil"),
    ("Egypt", "Africa/Cairo"),
    ("El Salvador", "America/El_Salvador"),
    ("Equatorial Guinea", "Africa/Malabo"),
    ("Eritrea", "Africa/Asmara"),
    ("Estonia", "Europe/Tallinn"),
    ("Eswatini", "Africa/Mbabane"),
    ("Ethiopia", "Africa/Addis_Ababa"),
    ("Fiji", "Pacific/Fiji"),
    ("Finland", "Europe/Helsinki"),
    ("France", "Europe/Paris"),
    ("Gabon", "Africa/Libreville"),
    ("Gambia", "Africa/Banjul"),
    ("Georgia", "Asia/Tbilisi"),
    ("Germany", "Europe/Berlin"),
    ("Ghana", "Africa/Accra"),
    ("Greece", "Europe/Athens"),
    ("Grenada", "America/Grenada"),
    ("Guatemala", "America/Guatemala"),
    ("Guinea", "Africa/Conakry"),
    ("Guinea-Bissau", "Africa/Bissau"),
    ("Guyana", "America/Guyana"),
    ("Haiti", "America/Port-au-Prince"),
    ("Honduras", "America/Tegucigalpa"),
    ("Hungary", "Europe/Budapest"),
    ("Iceland", "Atlantic/Reykjavik"),
    ("India", "Asia/Kolkata"),
    ("Indonesia — West", "Asia/Jakarta"),
    ("Indonesia — Central", "Asia/Makassar"),
    ("Indonesia — East", "Asia/Jayapura"),
    ("Iran", "Asia/Tehran"),
    ("Iraq", "Asia/Baghdad"),
    ("Ireland", "Europe/Dublin"),
    ("Israel", "Asia/Jerusalem"),
    ("Italy", "Europe/Rome"),
    ("Jamaica", "America/Jamaica"),
    ("Japan", "Asia/Tokyo"),
    ("Jordan", "Asia/Amman"),
    ("Kazakhstan — West", "Asia/Aqtau"),
    ("Kazakhstan — East", "Asia/Almaty"),
    ("Kenya", "Africa/Nairobi"),
    ("Kiribati — West", "Pacific/Tarawa"),
    ("Kiribati — East", "Pacific/Kiritimati"),
    ("Korea, North", "Asia/Pyongyang"),
    ("Korea, South", "Asia/Seoul"),
    ("Kosovo", "Europe/Belgrade"),
    ("Kuwait", "Asia/Kuwait"),
    ("Kyrgyzstan", "Asia/Bishkek"),
    ("Laos", "Asia/Vientiane"),
    ("Latvia", "Europe/Riga"),
    ("Lebanon", "Asia/Beirut"),
    ("Lesotho", "Africa/Maseru"),
    ("Liberia", "Africa/Monrovia"),
    ("Libya", "Africa/Tripoli"),
    ("Liechtenstein", "Europe/Zurich"),
    ("Lithuania", "Europe/Vilnius"),
    ("Luxembourg", "Europe/Luxembourg"),
    ("Madagascar", "Indian/Antananarivo"),
    ("Malawi", "Africa/Blantyre"),
    ("Malaysia", "Asia/Kuala_Lumpur"),
    ("Maldives", "Indian/Maldives"),
    ("Mali", "Africa/Bamako"),
    ("Malta", "Europe/Malta"),
    ("Marshall Islands", "Pacific/Majuro"),
    ("Mauritania", "Africa/Nouakchott"),
    ("Mauritius", "Indian/Mauritius"),
    ("Mexico — Central", "America/Mexico_City"),
    ("Mexico — Northwest", "America/Tijuana"),
    ("Micronesia", "Pacific/Chuuk"),
    ("Moldova", "Europe/Chisinau"),
    ("Monaco", "Europe/Monaco"),
    ("Mongolia — West", "Asia/Hovd"),
    ("Mongolia — East", "Asia/Ulaanbaatar"),
    ("Montenegro", "Europe/Podgorica"),
    ("Morocco", "Africa/Casablanca"),
    ("Mozambique", "Africa/Maputo"),
    ("Myanmar", "Asia/Yangon"),
    ("Namibia", "Africa/Windhoek"),
    ("Nauru", "Pacific/Nauru"),
    ("Nepal", "Asia/Kathmandu"),
    ("Netherlands", "Europe/Amsterdam"),
    ("New Zealand", "Pacific/Auckland"),
    ("Nicaragua", "America/Managua"),
    ("Niger", "Africa/Niamey"),
    ("Nigeria", "Africa/Lagos"),
    ("North Macedonia", "Europe/Skopje"),
    ("Norway", "Europe/Oslo"),
    ("Oman", "Asia/Muscat"),
    ("Pakistan", "Asia/Karachi"),
    ("Palau", "Pacific/Palau"),
    ("Palestine", "Asia/Gaza"),
    ("Panama", "America/Panama"),
    ("Papua New Guinea", "Pacific/Port_Moresby"),
    ("Paraguay", "America/Asuncion"),
    ("Peru", "America/Lima"),
    ("Philippines", "Asia/Manila"),
    ("Poland", "Europe/Warsaw"),
    ("Portugal", "Europe/Lisbon"),
    ("Qatar", "Asia/Qatar"),
    ("Romania", "Europe/Bucharest"),
    ("Russia — Kaliningrad", "Europe/Kaliningrad"),
    ("Russia — Moscow", "Europe/Moscow"),
    ("Russia — Yekaterinburg", "Asia/Yekaterinburg"),
    ("Russia — Krasnoyarsk", "Asia/Krasnoyarsk"),
    ("Russia — Irkutsk", "Asia/Irkutsk"),
    ("Russia — Vladivostok", "Asia/Vladivostok"),
    ("Rwanda", "Africa/Kigali"),
    ("Saint Kitts & Nevis", "America/St_Kitts"),
    ("Saint Lucia", "America/St_Lucia"),
    ("Saint Vincent", "America/St_Vincent"),
    ("Samoa", "Pacific/Apia"),
    ("San Marino", "Europe/San_Marino"),
    ("São Tomé & Príncipe", "Africa/Sao_Tome"),
    ("Saudi Arabia", "Asia/Riyadh"),
    ("Senegal", "Africa/Dakar"),
    ("Serbia", "Europe/Belgrade"),
    ("Seychelles", "Indian/Mahe"),
    ("Sierra Leone", "Africa/Freetown"),
    ("Singapore", "Asia/Singapore"),
    ("Slovakia", "Europe/Bratislava"),
    ("Slovenia", "Europe/Ljubljana"),
    ("Solomon Islands", "Pacific/Guadalcanal"),
    ("Somalia", "Africa/Mogadishu"),
    ("South Africa", "Africa/Johannesburg"),
    ("South Sudan", "Africa/Juba"),
    ("Spain", "Europe/Madrid"),
    ("Sri Lanka", "Asia/Colombo"),
    ("Sudan", "Africa/Khartoum"),
    ("Suriname", "America/Paramaribo"),
    ("Sweden", "Europe/Stockholm"),
    ("Switzerland", "Europe/Zurich"),
    ("Syria", "Asia/Damascus"),
    ("Taiwan", "Asia/Taipei"),
    ("Tajikistan", "Asia/Dushanbe"),
    ("Tanzania", "Africa/Dar_es_Salaam"),
    ("Thailand", "Asia/Bangkok"),
    ("Timor-Leste", "Asia/Dili"),
    ("Togo", "Africa/Lome"),
    ("Tonga", "Pacific/Tongatapu"),
    ("Trinidad & Tobago", "America/Port_of_Spain"),
    ("Tunisia", "Africa/Tunis"),
    ("Turkey", "Europe/Istanbul"),
    ("Turkmenistan", "Asia/Ashgabat"),
    ("Tuvalu", "Pacific/Funafuti"),
    ("Uganda", "Africa/Kampala"),
    ("Ukraine", "Europe/Kyiv"),
    ("United Arab Emirates", "Asia/Dubai"),
    ("United Kingdom", "Europe/London"),
    ("United States — Eastern", "America/New_York"),
    ("United States — Central", "America/Chicago"),
    ("United States — Mountain", "America/Denver"),
    ("United States — Pacific", "America/Los_Angeles"),
    ("United States — Alaska", "America/Anchorage"),
    ("United States — Hawaii", "Pacific/Honolulu"),
    ("Uruguay", "America/Montevideo"),
    ("Uzbekistan", "Asia/Tashkent"),
    ("Vanuatu", "Pacific/Efate"),
    ("Vatican City", "Europe/Vatican"),
    ("Venezuela", "America/Caracas"),
    ("Vietnam", "Asia/Ho_Chi_Minh"),
    ("Yemen", "Asia/Aden"),
    ("Zambia", "Africa/Lusaka"),
    ("Zimbabwe", "Africa/Harare"),
    ("UTC", "UTC"),
]

REFERENCE_ZONES = [
    ("US/Eastern", "America/New_York"),
    ("US/Central", "America/Chicago"),
    ("US/Mountain", "America/Denver"),
    ("US/Pacific", "America/Los_Angeles"),
    ("UK/London", "Europe/London"),
    ("EU/Berlin", "Europe/Berlin"),
    ("EU/Paris", "Europe/Paris"),
    ("India/Mumbai", "Asia/Kolkata"),
    ("China/Shanghai", "Asia/Shanghai"),
    ("Japan/Tokyo", "Asia/Tokyo"),
    ("Australia/Sydney", "Australia/Sydney"),
    ("UTC", "UTC"),
]

# ── UTC offsets with common abbreviations ──
OFFSETS = [
    ("UTC-12", -12, "BIT — Baker Island"),
    ("UTC-11", -11, "SST — Midway, Pago Pago"),
    ("UTC-10", -10, "HST — Hawaii, Cook Islands"),
    ("UTC-9:30", -9.5, "MART — Marquesas Islands"),
    ("UTC-9", -9, "AKST — Alaska, Gambier Islands"),
    ("UTC-8", -8, "PST — Los Angeles, Vancouver"),
    ("UTC-7", -7, "MST — Denver, Calgary, Phoenix"),
    ("UTC-6", -6, "CST — Chicago, Mexico City"),
    ("UTC-5", -5, "EST — New York, Toronto, Lima"),
    ("UTC-4", -4, "AST — Santiago, Caracas, Halifax"),
    ("UTC-3", -3, "BRT — São Paulo, Buenos Aires"),
    ("UTC-2", -2, "GST — South Georgia"),
    ("UTC-1", -1, "CVT — Azores, Cape Verde"),
    ("UTC±0", 0, "GMT / WET — London, Lisbon, Dublin"),
    ("UTC+1", 1, "CET — Berlin, Paris, Rome, Lagos"),
    ("UTC+2", 2, "EET — Athens, Cairo, Kyiv, Jo'burg"),
    ("UTC+3", 3, "MSK / EAT — Moscow, Nairobi, Riyadh"),
    ("UTC+3:30", 3.5, "IRST — Tehran"),
    ("UTC+4", 4, "GST — Dubai, Baku, Mauritius"),
    ("UTC+4:30", 4.5, "AFT — Kabul"),
    ("UTC+5", 5, "PKT — Karachi, Tashkent, Maldives"),
    ("UTC+5:30", 5.5, "IST — India, Colombo"),
    ("UTC+5:45", 5.75, "NPT — Nepal (Kathmandu)"),
    ("UTC+6", 6, "BST — Dhaka, Almaty, Bishkek"),
    ("UTC+6:30", 6.5, "MMT — Yangon (Myanmar)"),
    ("UTC+7", 7, "ICT — Bangkok, Jakarta, Hanoi"),
    ("UTC+8", 8, "CST / AWST — Shanghai, Singapore, Perth"),
    ("UTC+8:45", 8.75, "CWST — Eucla (Western Australia)"),
    ("UTC+9", 9, "JST / KST — Tokyo, Seoul"),
    ("UTC+9:30", 9.5, "ACST — Darwin, Adelaide"),
    ("UTC+10", 10, "AEST — Sydney, Melbourne, Guam"),
    ("UTC+10:30", 10.5, "LHST — Lord Howe Island"),
    ("UTC+11", 11, "SBT — Solomon Islands, Vanuatu"),
    ("UTC+12", 12, "NZST — Auckland, Fiji, Nauru"),
    ("UTC+12:45", 12.75, "CHAST — Chatham Islands"),
    ("UTC+13", 13, "TOT — Tonga, Samoa"),
    ("UTC+14", 14, "LINT — Line Islands (Kiribati)"),
]
