import sqlite3
from shared import db_path

DB_PATH = db_path("tabs", "cheats", "cheats.db")


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db():
    conn = get_db()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS sheets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL UNIQUE,
            created_at TEXT DEFAULT (datetime('now'))
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sheet_id INTEGER NOT NULL,
            term TEXT NOT NULL,
            definition TEXT NOT NULL,
            created_at TEXT DEFAULT (datetime('now')),
            FOREIGN KEY (sheet_id) REFERENCES sheets(id) ON DELETE CASCADE
        )
    """)
    conn.commit()

    count = conn.execute("SELECT COUNT(*) FROM sheets").fetchone()[0]
    if count == 0:
        _seed_data(conn)

    conn.close()


# NONE OF THIS IS VERIFIED, TAKE IT WITH A GRAIN OF SALT.

def _seed_data(conn):
    sheets = [
        "Git Commands",
        "SQL Snippets",
        "Docker Commands",
        "Python Tips",
        "Linux Commands",
        "HTML",
        "CSS",
        "Python Libraries",
        "Markdown",
        "Regex",
        "Vim",
        "HTTP Status Codes",
        "SSH",
        "jq",
        "systemd",
        "tmux",
        "YAML",
        "crontab",
        "ffmpeg",
        "networking",
        "npm / Node Tooling",
        "Textual",
    ]

    entries = {
        "Git Commands": [
            ("git init", "Initialize a new Git repository in the current directory"),
            ("git clone <url>", "Clone a remote repository to your local machine"),
            ("git status", "Show the working tree status (changed, staged, untracked)"),
            ("git add <file>", "Stage changes in <file> for the next commit"),
            ("git add .", "Stage all changes in the current directory"),
            ("git commit -m \"msg\"", "Commit staged changes with a message"),
            ("git commit --amend", "Amend the last commit (edit message or add files)"),
            ("git log", "Show commit history"),
            ("git log --oneline", "Compact one-line commit history"),
            ("git log --graph --oneline", "Visualize branch topology in compact form"),
            ("git diff", "Show unstaged changes between working tree and index"),
            ("git diff --staged", "Show staged changes that will go into the next commit"),
            ("git diff HEAD~1", "Show changes introduced by the last commit"),
            ("git branch", "List local branches (* marks current)"),
            ("git branch <name>", "Create a new branch at the current commit"),
            ("git checkout <branch>", "Switch to an existing branch"),
            ("git checkout -b <name>", "Create and switch to a new branch in one step"),
            ("git merge <branch>", "Merge <branch> into the current branch"),
            ("git merge --abort", "Abort a merge in progress due to conflicts"),
            ("git rebase <branch>", "Reapply current branch commits on top of <branch>"),
            ("git rebase -i HEAD~3", "Interactively rebase the last 3 commits (squash/fixup)"),
            ("git push", "Push local commits to the remote tracking branch"),
            ("git push --force-with-lease", "Force-push safely (rejects if remote has new commits)"),
            ("git pull", "Fetch and merge changes from the remote"),
            ("git fetch", "Download remote changes without merging"),
            ("git stash", "Temporarily stash uncommitted changes"),
            ("git stash pop", "Restore the most recently stashed changes"),
            ("git stash list", "Show all stashed changes"),
            ("git reset --hard HEAD", "Discard all uncommitted changes (destructive)"),
            ("git reset HEAD~1", "Undo last commit, keep changes in working tree"),
            ("git revert <commit>", "Create a new commit that undoes a previous commit"),
            ("git remote -v", "List remote repositories with URLs"),
            ("git cherry-pick <commit>", "Apply a specific commit onto the current branch"),
            ("git tag v1.0", "Create a lightweight tag at the current commit"),
            ("git blame <file>", "Show who last changed each line of a file"),
        ],
        "SQL Snippets": [
            ("SELECT * FROM t", "Select all columns and rows from table t"),
            ("SELECT a, b FROM t WHERE c = 1", "Filtered select with a condition"),
            ("SELECT a, COUNT(*) FROM t GROUP BY a", "Group rows and count per group"),
            ("SELECT ... HAVING COUNT(*) > 1", "Filter groups (after GROUP BY)"),
            ("SELECT ... ORDER BY a DESC", "Sort results descending by column a"),
            ("SELECT ... LIMIT 10 OFFSET 20", "Paginate: skip 20 rows, return 10"),
            ("INSERT INTO t (a, b) VALUES (1, 'x')", "Insert a single row"),
            ("INSERT INTO t (a, b) VALUES (1,'x'), (2,'y')", "Insert multiple rows at once"),
            ("UPDATE t SET a = 2 WHERE b = 'x'", "Update rows matching a condition"),
            ("DELETE FROM t WHERE id = 5", "Delete rows matching a condition"),
            ("CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT NOT NULL)", "Create a new table"),
            ("ALTER TABLE t ADD COLUMN x TEXT", "Add a new column to an existing table"),
            ("DROP TABLE IF EXISTS t", "Safely drop a table (no error if missing)"),
            ("CREATE INDEX idx_name ON t (column)", "Create an index to speed up queries"),
            ("SELECT ... JOIN t2 ON t.id = t2.t_id", "Inner join on a foreign key"),
            ("SELECT ... LEFT JOIN t2 ON t.id = t2.t_id", "Left join (all left rows, nulls for right)"),
            ("SELECT ... WHERE x IN (1, 2, 3)", "Match any value in a list"),
            ("SELECT ... WHERE x BETWEEN 1 AND 10", "Range filter (inclusive)"),
            ("SELECT ... WHERE name LIKE 'A%'", "Pattern match: starts with 'A'"),
            ("SELECT ... WHERE name LIKE '%son'", "Pattern match: ends with 'son'"),
            ("SELECT ... WHERE col IS NULL", "Check for NULL (use IS, not =)"),
            ("SELECT COALESCE(col, 'default')", "Return first non-NULL value in the list"),
            ("SELECT DISTINCT a FROM t", "Return unique values of column a"),
            ("SELECT CASE WHEN x>0 THEN 'pos' ELSE 'neg' END", "Conditional expression in SELECT"),
            ("BEGIN; ... COMMIT;", "Wrap statements in a transaction"),
            ("ROLLBACK;", "Undo changes back to the last BEGIN"),
            ("PRAGMA table_info(t)", "Show column info for table t (SQLite)"),
            (".schema t", "Show CREATE TABLE statement (sqlite3 CLI)"),
        ],
        "Docker Commands": [
            ("docker run <image>", "Create and start a container from an image"),
            ("docker run -d <image>", "Run container in detached (background) mode"),
            ("docker run -it <image> bash", "Run interactively with a shell"),
            ("docker run -p 8080:80 <image>", "Map host port 8080 to container port 80"),
            ("docker run -v /host:/container <img>", "Mount a host directory into the container"),
            ("docker run -e VAR=val <img>", "Set an environment variable in the container"),
            ("docker run --name foo <image>", "Assign a custom name to the container"),
            ("docker run --rm <image>", "Auto-remove the container when it exits"),
            ("docker ps", "List running containers"),
            ("docker ps -a", "List all containers (including stopped)"),
            ("docker stop <container>", "Gracefully stop a running container (SIGTERM)"),
            ("docker kill <container>", "Force-stop a container (SIGKILL)"),
            ("docker start <container>", "Start a stopped container"),
            ("docker restart <container>", "Stop and start a container"),
            ("docker rm <container>", "Remove a stopped container"),
            ("docker rm -f <container>", "Force-remove a running container"),
            ("docker images", "List downloaded images"),
            ("docker rmi <image>", "Remove an image"),
            ("docker pull <image>", "Download an image from a registry"),
            ("docker build -t name .", "Build an image from a Dockerfile in current dir"),
            ("docker exec -it <c> bash", "Open an interactive shell inside a running container"),
            ("docker logs <container>", "Show stdout/stderr logs of a container"),
            ("docker logs -f <container>", "Follow container logs in real time (tail -f)"),
            ("docker compose up", "Start services defined in docker-compose.yml"),
            ("docker compose up -d", "Start services in detached mode"),
            ("docker compose down", "Stop and remove services, networks, volumes"),
            ("docker compose ps", "List services and their status"),
            ("docker system prune -a", "Remove all unused containers, images, networks, cache"),
            ("docker inspect <container>", "Show detailed container info in JSON"),
            ("docker cp <c>:/path ./local", "Copy files from a container to the host"),
            ("docker stats", "Live resource usage for all running containers"),
        ],
        "Python Tips": [
            ("[x**2 for x in range(10)]", "List comprehension: squares 0 through 81"),
            ("[x for x in lst if x > 0]", "Filter list to only positive values"),
            ("{k: v for k, v in pairs}", "Dict comprehension from a list of (key, value) tuples"),
            ("{x for x in lst if x}", "Set comprehension: unique truthy values"),
            ("enumerate(lst, start=0)", "Iterate with index: for i, val in enumerate(lst)"),
            ("zip(a, b, strict=True)", "Pair iterables (strict raises if lengths differ, 3.10+)"),
            ("sorted(lst, key=lambda x: x.attr)", "Sort by an attribute or custom key"),
            ("any(cond for x in lst)", "True if at least one element matches condition"),
            ("all(cond for x in lst)", "True if all elements match condition"),
            ("with open('f') as f: ...", "Context manager: auto-closes the file on block exit"),
            ("try: ... except E as e: ... finally: ...", "Exception handling with guaranteed cleanup"),
            ("collections.defaultdict(list)", "Dict that auto-creates missing keys with a default factory"),
            ("collections.Counter(lst)", "Count hashable items: Counter(['a','a','b']) is {'a':2, 'b':1}"),
            ("collections.namedtuple('Pt', 'x y')", "Lightweight object with named fields"),
            ("itertools.chain(a, b, c)", "Flatten multiple iterables into one lazy sequence"),
            ("itertools.product(a, b)", "Cartesian product of iterables"),
            ("itertools.combinations(lst, 2)", "All unique pairs from lst"),
            ("f\"Hello {name}, you are {age}\"", "f-string formatting (Python 3.6+)"),
            ("f\"{value=}\" or f\"{value:.2f}\"", "Debug print with = sign; format to 2 decimal places"),
            ("pathlib.Path('dir') / 'sub' / 'file.txt'", "Build paths with / operator (modern, cross-platform)"),
            ("python -m http.server 8000", "Serve current directory over HTTP (terminal one-liner)"),
            ("json.dumps(obj, indent=2, ensure_ascii=False)", "Pretty-print a dict/list as JSON"),
            ("random.choice(lst) / random.sample(lst, k=3)", "Pick 1 or k unique random elements"),
            ("time.perf_counter()", "High-resolution monotonic timer for benchmarking"),
            ("breakpoint()", "Drop into pdb debugger at this line (Python 3.7+)"),
            ("textwrap.dedent(s)", "Remove common leading whitespace from multi-line strings"),
            ("functools.lru_cache(maxsize=128)", "Memoize function results with an LRU cache"),
            ("re.sub(r'\\d+', '', s)", "Regex: remove all digits from a string"),
            ("s.split() / s.strip() / ' '.join(lst)", "Common string operations"),
            ("__name__ == '__main__'", "Guard: only run when executed directly (not imported)"),
        ],
        "Linux Commands": [
            ("ls -la", "List all files in long format, including hidden (.files)"),
            ("cd -", "Switch to the previous directory"),
            ("pwd", "Print working (current) directory path"),
            ("find . -name '*.py'", "Find files matching a glob pattern recursively"),
            ("find . -type f -mtime -7", "Find files modified in the last 7 days"),
            ("find . -type f -size +10M", "Find files larger than 10 MB"),
            ("grep -r 'pattern' .", "Recursively search for a pattern in files"),
            ("grep -v 'pattern' file", "Invert match (lines NOT containing pattern)"),
            ("grep -c 'pattern' file", "Count matching lines"),
            ("grep -n 'pattern' file", "Show line numbers of matches"),
            ("du -sh * | sort -h", "Disk usage per file/dir, sorted human-readable"),
            ("df -h", "Show free disk space on all mounted filesystems"),
            ("free -h", "Show available and used memory"),
            ("ps aux | grep <name>", "Find processes by name"),
            ("kill -9 <PID>", "Force-kill a process by PID (SIGKILL)"),
            ("kill -15 <PID>", "Gracefully terminate a process (SIGTERM, default)"),
            ("chmod +x script.sh", "Make a file executable"),
            ("chmod 755 dir", "Set rwxr-xr-x (owner full, others read+execute)"),
            ("chown user:group file", "Change file owner and group"),
            ("tar -czvf archive.tar.gz dir/", "Create a gzipped tarball"),
            ("tar -xzvf archive.tar.gz", "Extract a gzipped tarball"),
            ("| (pipe)", "Send stdout of left command to stdin of right: ls | wc -l"),
            ("> file", "Redirect stdout to file (overwrite): echo hi > file.txt"),
            (">> file", "Redirect stdout to file (append): echo hi >> file.txt"),
            ("2>&1", "Redirect stderr to stdout: cmd 2>&1 | grep error"),
            ("&", "Run command in background: long_running_cmd &"),
            ("Ctrl+R", "Reverse-search command history interactively"),
            ("!!", "Re-run the last command (useful with sudo: sudo !!)"),
            ("!$", "Last argument of the previous command"),
            ("tee file", "Write stdin to both stdout and a file: cmd | tee log.txt"),
            ("xargs", "Build commands from stdin: find . -name '*.tmp' | xargs rm"),
            ("sed 's/foo/bar/g' file", "Replace all occurrences of 'foo' with 'bar'"),
            ("sed -i 's/foo/bar/g' file", "In-place replace in a file (no backup)"),
            ("awk '{print $2}' file", "Print the second column of each line"),
            ("awk -F: '{print $1}' /etc/passwd", "Use custom field separator"),
            ("ln -s /target linkname", "Create a symbolic link (symlink)"),
            ("alias ll='ls -la'", "Create a command shortcut (persist in ~/.bashrc)"),
            ("history | tail -20", "Show last 20 commands from shell history"),
            ("head -n 5 file / tail -n 5 file", "First/last 5 lines of a file"),
            ("wc -l file", "Count lines (-w for words, -c for chars)"),
            ("sort file | uniq", "Sort and deduplicate lines"),
            ("sort file | uniq -c | sort -rn", "Count and sort unique lines by frequency"),
            ("diff file1 file2", "Show line-by-line differences between two files"),
            ("watch -n 2 <command>", "Re-run a command every 2 seconds (live monitoring)"),
            ("curl -s https://example.com", "Fetch a URL silently (no progress bar)"),
        ],
        "HTML": [
            ("<!DOCTYPE html>", "Declares the document as HTML5 (must be the very first line)"),
            ("<html lang=\"en\">", "Root element; set language for accessibility and SEO"),
            ("<head>", "Metadata container: title, charset, viewport, styles, scripts"),
            ("<meta charset=\"UTF-8\">", "Character encoding declaration (place early in <head>)"),
            ("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", "Responsive viewport: match device width, set initial zoom"),
            ("<title>Page Title</title>", "Browser tab title (also used by search engines)"),
            ("<link rel=\"stylesheet\" href=\"style.css\">", "Link an external CSS stylesheet"),
            ("<script src=\"app.js\" defer></script>", "Load external JS; defer = run after HTML parse"),
            ("<body>", "All visible page content goes inside <body>"),
            ("<h1> to <h6>", "Headings: h1 (most important, one per page) to h6 (least)"),
            ("<p>", "Paragraph of text (block element, adds vertical spacing)"),
            ("<a href=\"url\">link text</a>", "Hyperlink; use target=\"_blank\" for new tab"),
            ("<img src=\"img.jpg\" alt=\"description\">", "Image; alt is required for accessibility (screen readers)"),
            ("<ul><li>item</li></ul>", "Unordered (bulleted) list"),
            ("<ol><li>item</li></ol>", "Ordered (numbered) list"),
            ("<div>", "Generic block container: use for layout groupings"),
            ("<span>", "Generic inline container: use for text-level styling"),
            ("<strong> / <em>", "Semantic bold and italic (prefer over <b> / <i>)"),
            ("<br>", "Line break (self-closing; don't use for spacing — use CSS)"),
            ("<hr>", "Horizontal rule / thematic break"),
            ("<!-- comment -->", "HTML comment (not rendered, visible in page source)"),
            ("<header> / <footer>", "Semantic page/section header and footer"),
            ("<nav>", "Semantic navigation container (menus, breadcrumbs)"),
            ("<main>", "Semantic main content (one per page, excludes header/footer/nav)"),
            ("<article> / <section>", "Self-contained content / thematic grouping of content"),
            ("<aside>", "Tangentially related content (sidebar, pull quote, ad)"),
            ("<table>", "Table container: use <tr> rows, <td> cells, <th> headers"),
            ("<form action=\"/submit\" method=\"POST\">", "Form container: action = submit URL, method = GET or POST"),
            ("<input type=\"text\" name=\"u\" placeholder=\"...\">", "Text input; types: text, password, email, number, date, file, checkbox, radio, submit"),
            ("<textarea rows=\"4\" name=\"msg\"></textarea>", "Multi-line text input"),
            ("<select name=\"choice\"><option value=\"a\">A</option></select>", "Dropdown select menu"),
            ("<button type=\"submit\">Send</button>", "Button; type can be submit, reset, or button (default is submit!)"),
            ("<label for=\"id\">Name:</label>", "Label linked to input by id: improves accessibility and click target"),
            ("<details><summary>Click me</summary>content</details>", "Native collapsible/accordion without JavaScript"),
            ("<code> / <pre>", "Inline code / preformatted block (preserves whitespace)"),
        ],
        "CSS": [
            ("selector { property: value; }", "Basic CSS rule: target element(s), apply declarations"),
            ("* { box-sizing: border-box; }", "Universal reset: padding/border included in width/height"),
            (".classname", "Class selector: targets elements with class=\"classname\""),
            ("#idname", "ID selector: targets the unique element with id=\"idname\""),
            ("div p", "Descendant selector: all <p> anywhere inside a <div>"),
            ("div > p", "Child selector: <p> that is a direct child of <div>"),
            ("h1, h2, h3", "Group selector: applies to all comma-separated selectors"),
            (":hover / :focus / :active", "Pseudo-classes: mouse hover, keyboard focus, active click"),
            ("::before / ::after", "Pseudo-elements: insert generated content (requires content: '')"),
            ("color: #333;", "Text color (hex, rgb(), hsl(), named colors)"),
            ("background: #f5f5f5;", "Background shorthand: color image repeat position/size"),
            ("margin: 16px auto;", "Space outside element; auto centers block elements horizontally"),
            ("padding: 8px 16px;", "Space inside element; 2 values = top/bottom right/left"),
            ("border: 1px solid #ccc;", "Border shorthand: width style color"),
            ("border-radius: 8px;", "Rounded corners; 50% = circle on square element"),
            ("width: 100%; max-width: 800px;", "Full width up to a max; responsive pattern"),
            ("display: flex;", "Flexbox container: children become flex items (one-dimensional layout)"),
            ("flex-direction: row | column;", "Main axis direction for flex items"),
            ("justify-content: center | space-between;", "Align flex items along the main axis"),
            ("align-items: center | stretch;", "Align flex items along the cross axis"),
            ("gap: 16px;", "Spacing between flex/grid items (replaces old margin hacks)"),
            ("display: grid;", "Grid container: two-dimensional layout system"),
            ("grid-template-columns: 1fr 2fr 1fr;", "Define grid column widths; fr = fraction of available space"),
            ("grid-template-columns: repeat(3, 1fr);", "Shorthand: 3 equal columns"),
            ("grid-template-rows: auto 1fr auto;", "Sticky-footer layout: header, content, footer"),
            ("position: relative | absolute | fixed | sticky;", "Positioning: relative=offset from self, absolute=offset from positioned ancestor, fixed=viewport, sticky=scrolls then sticks"),
            ("z-index: 10;", "Stacking order (higher = on top; only works on positioned elements)"),
            ("overflow: auto | hidden | scroll;", "What happens when content overflows the box"),
            ("font-family: 'Inter', sans-serif;", "Font stack: preferred font, fallback generic family"),
            ("font-size: 1rem;", "rem = relative to root font size (accessible, user-respectful)"),
            ("line-height: 1.5;", "Line spacing multiplier (unitless preferred — scales with font-size)"),
            ("text-align: center | left | right;", "Horizontal text alignment"),
            ("opacity: 0.5;", "Transparency: 0 = invisible, 1 = fully opaque"),
            ("transition: all 0.2s ease;", "Animate property changes: property duration timing-function"),
            ("cursor: pointer;", "Mouse cursor style: pointer = hand, not-allowed, grab, etc."),
            ("@media (max-width: 768px) { ... }", "Media query: apply styles when viewport is 768px or narrower (mobile)"),
        ],
        "Python Libraries": [
            ("pathlib — Path('dir') / 'file'", "Modern file paths: / operator, .read_text(), .glob(), .mkdir()"),
            ("datetime — datetime.now(), timedelta(days=7)", "Dates, times, deltas, formatting (strftime/strptime)"),
            ("collections — defaultdict, Counter, deque, namedtuple", "Specialised container datatypes beyond dict/list/set"),
            ("itertools — chain, product, combinations, groupby", "Lazy iteration: cartesian product, grouping, flattening"),
            ("functools — lru_cache, reduce, partial, wraps", "Higher-order functions: memoization, reduction, decorator helpers"),
            ("re — re.search(r'\\d+', s), re.sub(r'a', 'b', s)", "Regular expressions: find, replace, split, compile"),
            ("json — json.load(f) / json.dumps(obj, indent=2)", "JSON encode/decode; serialise Python objects to/from JSON"),
            ("csv — csv.reader(f) / csv.DictWriter(f, fieldnames=...)", "CSV file reading and writing with dict or list rows"),
            ("sqlite3 — conn.execute('SELECT ...', params)", "Built-in SQLite database: no server, no setup, ACID transactions"),
            ("argparse — ArgumentParser, add_argument, parse_args", "CLI argument parsing: positional, optional, flags, help text"),
            ("logging — logging.getLogger, .info(), .warning()", "Structured logging with levels, handlers, formatters"),
            ("dataclasses — @dataclass class P: x: int; y: int", "Auto-generate __init__, __repr__, __eq__ from type annotations"),
            ("typing — List[str], Optional[int], Union, Protocol", "Type hints for static checkers (mypy, pyright) and IDE support"),
            ("os — os.getenv('HOME'), os.listdir(), os.makedirs()", "OS interactions: env vars, directories, process, path separators"),
            ("subprocess — subprocess.run(['ls', '-la'], capture_output=True)", "Run external commands, capture stdout/stderr, check return codes"),
            ("hashlib — hashlib.sha256(data).hexdigest()", "Cryptographic hashes: md5, sha1, sha256, blake2b"),
            ("uuid — uuid.uuid4()", "Generate random UUIDs (v4 = random, v1 = time-based, v5 = namespace)"),
            ("secrets — secrets.token_hex(16)", "Cryptographically secure random tokens (prefer over random for security)"),
            ("tempfile — tempfile.NamedTemporaryFile() / mkdtemp()", "Create temporary files/dirs that auto-clean on close or interpreter exit"),
            ("textwrap — textwrap.dedent(s) / .fill(s, width=70)", "Dedent multi-line strings, wrap paragraphs to a given width"),
            ("requests — requests.get(url, headers=...).json()", "HTTP client: GET, POST, sessions, auth, streaming (pip install requests)"),
            ("flask — @app.route('/') -> return render_template(...)", "Micro web framework: routes, templates (Jinja2), request/response"),
            ("fastapi — @app.get('/items/{id}') -> return JSON", "Fast async web framework with auto OpenAPI docs and type validation"),
            ("pydantic — class User(BaseModel): name: str; age: int", "Data validation via type annotations; parses dicts/JSON into typed models"),
            ("rich — rich.print('[bold red]hello[/]'), Console, Table", "Beautiful terminal formatting: colours, tables, progress bars, markdown"),
            ("click — @click.command(); @click.option('--name')", "Composible CLI framework: commands, options, arguments, prompts"),
            ("pytest — def test_foo(): assert func() == 42", "Test framework: auto-discovery, fixtures, parametrise, mocking (pip install pytest)"),
            ("tqdm — for x in tqdm(items): process(x)", "Drop-in progress bar for loops, with speed, ETA, and rate"),
            ("pillow — Image.open('a.png').resize((w,h)).save('b.jpg')", "Image processing: resize, crop, rotate, convert formats (PIL fork)"),
            ("numpy — np.array([1,2,3]), np.linspace, np.random.randn", "Fast N-dimensional arrays: linear algebra, stats, broadcasting"),
            ("pandas — pd.read_csv('data.csv'), df.groupby('col').mean()", "DataFrames: load, filter, group, join, pivot (pip install pandas)"),
            ("matplotlib — plt.plot(x, y); plt.title('X vs Y'); plt.show()", "Plotting: line, scatter, bar, histogram, subplots, styling"),
        ],
        "Markdown": [
            ("# H1 / ## H2 / ### H3", "Headings: 1-6 hash marks; H1 = page title, H2 = sections"),
            ("**bold** / *italic* / ***both***", "Text emphasis: double asterisk = bold, single = italic"),
            ("~~strikethrough~~", "Strikethrough text"),
            ("[link text](https://example.com)", "Inline link: display text in brackets, URL in parens"),
            ("[link][ref] ... [ref]: url", "Reference-style link: define URL once, reference by label"),
            ("![alt text](image.jpg)", "Image: bang + link syntax; alt text for accessibility"),
            ("`inline code`", "Inline code: backticks for monospace"),
            ("```python\ncode\n```", "Fenced code block: triple backticks + optional language for syntax highlighting"),
            ("- item / * item / + item", "Unordered list: dash, asterisk, or plus (dash most common)"),
            ("1. First\n2. Second", "Ordered list: number + period; actual numbers don't matter (all 1. works)"),
            ("- [ ] task / - [x] done", "Task list: checkbox in a list item (GitHub-flavoured)"),
            ("> blockquote", "Blockquote: > prefix; nested with >>; can contain other Markdown"),
            ("--- / *** / ___", "Horizontal rule: three or more dashes, asterisks, or underscores on their own line"),
            ("| Col A | Col B |\n|---|---|\n| a | b |", "Table: pipe-delimited columns; header separator with dashes; align with :--, :--:, --:"),
            ("**Header**|**Value**\n---|---\nFoo|Bar", "Minimal table style (no surrounding pipes required)"),
            ("[TOC] or <!-- toc -->", "Table of contents (supported by some renderers; auto-generated from headings)"),
            ("<!-- comment -->", "HTML comment: hidden from rendered output"),
            ("First line  \nsecond line", "Line break: end line with two spaces then newline (or use <br>)"),
            ("Two newlines = new paragraph", "Paragraph break: blank line between blocks of text"),
            ("[![alt](img)](url)", "Linked image: nest image inside link (clickable thumbnail)"),
            ("` `` ` -> literal backtick", "Escape backticks: wrap in double backticks if code contains a backtick"),
            ("\\* \\_ \\[ \\] \\( \\) \\# \\`", "Literal chars: backslash-escape special Markdown characters"),
            ("- [x] Supports **formatting**", "Rich formatting inside list items and table cells"),
            ("footnote[^1] ... [^1]: text", "Footnotes: reference in text, define anywhere (some renderers)"),
            ("term\n: definition", "Definition list: term on one line, colon + definition indented below"),
            ("#tag or @mention", "Not standard but widely recognised in issue trackers and wikis"),
        ],
        "Regex": [
            (". (dot)", "Matches any single character except newline"),
            ("^ / $", "Anchors: start of string / end of string"),
            ("\\bword\\b", "Word boundary: match whole word only (not 'password' inside 'password123')"),
            ("\\d", "Digit: [0-9]; \\D = non-digit"),
            ("\\w", "Word character: [a-zA-Z0-9_]; \\W = non-word"),
            ("\\s", "Whitespace: space, tab, newline; \\S = non-whitespace"),
            ("[abc]", "Character set: match a, b, or c (exactly one character)"),
            ("[^abc]", "Negated set: match anything EXCEPT a, b, c"),
            ("[a-z] / [0-9]", "Range: lowercase a to z / digit 0 to 9"),
            ("*", "Zero or more of the preceding token (greedy)"),
            ("+", "One or more of the preceding token (greedy)"),
            ("?", "Zero or one of the preceding token (optional); also makes * and + lazy: *? +?"),
            ("{n}", "Exactly n occurrences: \\d{3} matches 3 digits"),
            ("{n,}", "n or more occurrences"),
            ("{n,m}", "Between n and m occurrences (inclusive)"),
            ("(abc)", "Capturing group: captures matched text for backreference or extraction"),
            ("(?:abc)", "Non-capturing group: group without capturing (more efficient)"),
            ("a|b", "Alternation: match a OR b (use groups for scope: cat|dog)"),
            ("(?=...)", "Positive lookahead: assert what follows matches (doesn't consume)"),
            ("(?!...)", "Negative lookahead: assert what follows does NOT match"),
            ("(?<=...)", "Positive lookbehind: assert what precedes matches (fixed width)"),
            ("(?<!...)", "Negative lookbehind: assert what precedes does NOT match"),
            ("re.IGNORECASE / re.I", "Flag: case-insensitive matching"),
            ("re.MULTILINE / re.M", "Flag: ^ and $ match start/end of each line, not just whole string"),
            ("re.DOTALL / re.S", "Flag: . matches newline too"),
            ("re.VERBOSE / re.X", "Flag: ignore whitespace and #comments in pattern (write readable regex)"),
            ("re.compile(pattern, flags)", "Pre-compile a regex for repeated use (faster than inline)"),
            (r"re.sub(r'\\d+', '', s)", "Replace all digits with empty string (remove digits)"),
            (r"re.findall(r'\\w+', s)", "Return list of all word sequences in s"),
            (r"re.search(r'pattern', s)", "Find first match anywhere in s (returns Match or None)"),
            ("Email: r'[\\w.-]+@[\\w.-]+\\.\\w+'", "Rough email pattern (use a library for production validation)"),
            ("URL: r'https?://[\\w./-]+'", "Rough HTTP(S) URL pattern"),
            ("Phone: r'\\+?\\d[\\d -]{7,}\\d'", "Rough international phone number pattern"),
            ("Date YYYY-MM-DD: r'\\d{4}-\\d{2}-\\d{2}'", "Matches ISO-format dates like 2026-05-31"),
            ("IP (IPv4): r'\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}'", "Rough IPv4 address pattern"),
        ],
        "Vim": [
            ("i / a / o / O", "Enter insert mode: at cursor / after cursor / new line below / new line above"),
            ("Esc / Ctrl+[", "Return to Normal mode from any mode"),
            ("h j k l", "Move cursor: left / down / up / right (home-row muscle memory)"),
            ("w / b / e", "Word forward / word backward / end of word"),
            ("0 / ^ / $", "Jump to: start of line / first non-blank char / end of line"),
            ("gg / G", "Go to top of file / bottom of file"),
            ("<n>G or :<n>", "Go to line n (e.g. :42 = line 42)"),
            ("{ / }", "Jump to previous/next blank line (paragraph)"),
            ("%", "Jump to matching bracket/paren/brace"),
            ("x / dd / yy / p / P", "Delete char / delete line / yank (copy) line / paste after / paste before"),
            ("dw / d2w / diw", "Delete: word / 2 words / inner word (cursor anywhere in word)"),
            ("ciw / caw", "Change: inner word / a word (delete word and enter insert mode)"),
            ("ci\" / ci( / ci[", "Change inside: quotes / parens / brackets (replace contents)"),
            ("di\" / da\"", "Delete: inside quotes / around quotes (includes the quotes)"),
            ("yiw / yap", "Yank: inner word / around paragraph"),
            ("u / Ctrl+r", "Undo / redo"),
            (". (dot)", "Repeat the last change (Vim superpower)"),
            ("/pattern / ?pattern", "Search forward / backward; n = next match, N = previous"),
            (":%s/old/new/g", "Substitute: replace all 'old' with 'new' in entire file"),
            (":%s/old/new/gc", "Substitute with confirmation prompt on each match"),
            (":s/old/new/g", "Substitute in current line only"),
            ("* / #", "Search forward/backward for word under cursor"),
            ("v / V / Ctrl+v", "Visual mode: character / line / block (column) selection"),
            ("> / < (in visual mode)", "Indent / dedent selected lines"),
            ("= (in visual mode)", "Auto-indent selected lines based on filetype"),
            (">> / << / ==", "Indent / dedent / auto-indent current line"),
            (":w / :q / :wq / :q!", "Save / quit / save+quit / quit without saving"),
            ("ZZ / ZQ", "Save and quit / quit without saving (from Normal mode)"),
            (":e <file>", "Open (edit) another file in the current window"),
            (":sp / :vsp <file>", "Horizontal / vertical split with optional file"),
            ("Ctrl+w h/j/k/l or Ctrl+w w", "Navigate between splits; w = cycle forward"),
            ("Ctrl+w = / _ / |", "Equalize splits / maximise height / maximise width"),
            (":tabnew / gt / gT / :tabclose", "Tabs: new tab / next tab / previous tab / close tab"),
            ("ma / 'a", "Set mark 'a' at cursor / jump to mark 'a' (a-z are file-local, A-Z are global)"),
            ("q<letter> ... q / @<letter>", "Record macro to register <letter> / replay macro"),
            ("<n>@@", "Replay the last macro n times (e.g. 10@@ = 10 times)"),
            ("r<char> / R", "Replace single character / enter Replace mode (overtype)"),
            ("~", "Toggle case of character under cursor"),
        ],
        "HTTP Status Codes": [
            ("1xx — Informational", "Request received, continuing process"),
            ("200 OK", "Request succeeded (GET: data returned, POST: resource created/updated)"),
            ("201 Created", "Resource successfully created (returned with Location header)"),
            ("204 No Content", "Success with no response body (common for DELETE, PUT updates)"),
            ("301 Moved Permanently", "Resource has a new permanent URL (browsers cache the redirect)"),
            ("302 Found / 307 Temporary Redirect", "Resource temporarily at different URL; 307 preserves HTTP method"),
            ("304 Not Modified", "Cached version is still fresh (conditional GET with ETag/If-Modified-Since)"),
            ("400 Bad Request", "Malformed request syntax (invalid JSON, missing required field)"),
            ("401 Unauthorized", "Authentication required (client must provide valid credentials)"),
            ("403 Forbidden", "Server understands request but refuses — auth won't help (insufficient permissions)"),
            ("404 Not Found", "Resource does not exist at this URL"),
            ("405 Method Not Allowed", "HTTP method not supported for this endpoint (e.g. POST on a GET-only route)"),
            ("409 Conflict", "Request conflicts with current server state (duplicate key, version mismatch)"),
            ("410 Gone", "Resource permanently deleted (more specific than 404; no forwarding address)"),
            ("418 I'm a teapot", "RFC 2324 joke — server refuses to brew coffee because it's a teapot (used as Easter egg)"),
            ("422 Unprocessable Entity", "Semantic error: valid syntax but content can't be processed (validation failure)"),
            ("429 Too Many Requests", "Rate limit exceeded; Retry-After header tells when to back off"),
            ("500 Internal Server Error", "Generic server-side failure (unhandled exception, config error)"),
            ("502 Bad Gateway", "Upstream server returned invalid response (proxy/gateway error)"),
            ("503 Service Unavailable", "Server temporarily overloaded or under maintenance (retry later)"),
            ("504 Gateway Timeout", "Upstream server didn't respond in time (proxy timeout)"),
            ("200-299 = Success", "Request was received and processed correctly"),
            ("300-399 = Redirection", "Further action needed to complete the request"),
            ("400-499 = Client Error", "The client made a mistake (bad input, no auth, not found)"),
            ("500-599 = Server Error", "The server failed to fulfil a valid request"),
        ],
        "SSH": [
            ("ssh user@host", "Connect to host as user (default port 22)"),
            ("ssh -p 2222 user@host", "Connect on a non-standard port"),
            ("ssh -i ~/.ssh/mykey user@host", "Use a specific private key file for authentication"),
            ("ssh-keygen -t ed25519 -C \"email\"", "Generate a new Ed25519 key pair (modern, fast, secure)"),
            ("ssh-keygen -t rsa -b 4096 -C \"email\"", "Generate a 4096-bit RSA key pair (legacy-compatible)"),
            ("ssh-copy-id user@host", "Copy your public key to the remote host (enables passwordless login)"),
            ("ssh -L 8080:localhost:80 user@host", "Local port forwarding: local:8080 -> remote:80 via the SSH tunnel"),
            ("ssh -R 9090:localhost:3000 user@host", "Remote port forwarding: remote:9090 -> local:3000 via the SSH tunnel"),
            ("ssh -D 1080 user@host", "Dynamic SOCKS proxy: local:1080 -> any remote destination via the SSH tunnel"),
            ("ssh -N -f -L 8080:localhost:80 user@host", "Background tunnel: -N (no command) -f (background) — stays open"),
            ("ssh -A user@host", "Enable agent forwarding (use local keys from the remote machine; use with caution)"),
            ("ssh -J user@bastion user@target", "Jump host: connect to target through a bastion/gateway host"),
            ("scp file.txt user@host:/path/", "Copy file to remote host over SSH"),
            ("scp -r dir/ user@host:/path/", "Copy directory recursively to remote host"),
            ("scp user@host:/path/file.txt ./", "Copy file from remote host to local"),
            ("rsync -avz -e ssh dir/ user@host:/path/", "Rsync over SSH: archive mode, verbose, compress (-e ssh is default nowadays)"),
            ("sftp user@host", "Interactive SFTP session: get, put, ls, cd, rm, mkdir"),
            ("ssh -o ConnectTimeout=10 user@host", "Set connection timeout (10 seconds)"),
            ("ssh -o StrictHostKeyChecking=no user@host", "Skip host key verification (insecure — use only for ephemeral/known hosts)"),
            ("ssh -v / -vv / -vvv user@host", "Verbose/debug mode: -v = info, -vv = debug, -vvv = trace (great for troubleshooting)"),
            ("~/.ssh/config", "Per-host SSH config file: Host, HostName, User, Port, IdentityFile, ProxyJump"),
            ("Host myserver\n  HostName example.com\n  User deploy\n  Port 2222", "Example ~/.ssh/config entry: 'ssh myserver' expands to full connection string"),
            ("ssh -T git@github.com", "Test SSH connection to GitHub (no shell; -T disables PTY allocation)"),
            ("eval $(ssh-agent) / ssh-add", "Start SSH agent / add your private key to the agent (unlock once, reuse)"),
            ("ssh -t user@host 'sudo systemctl restart nginx'", "Force PTY allocation (-t) for sudo commands that need a terminal"),
            ("ssh user@host 'bash -s' < local_script.sh", "Run a local script on the remote host without copying it first"),
        ],
        "jq": [
            ("jq '.' file.json", "Pretty-print JSON (identity filter: output = input, formatted)"),
            ("jq '.key' file.json", "Extract value at key (also .key.subkey for nested objects)"),
            ("jq '.[0]' file.json", "First element of an array (.[-1] = last, .[1:3] = slice index 1-2)"),
            ("jq '.[]' file.json", "Unwrap array: output each element as a separate JSON object"),
            ("jq '.items[] | {name, price}'", "Pipe: extract items array, then select name and price fields from each"),
            ("jq '[.[] | .name]' file.json", "Collect .name from each array element into a new array (map equivalent)"),
            ("jq 'map(.name)' file.json", "Built-in map: same as [ .[] | .name ] — apply filter to each element"),
            ("jq '.[] | select(.price > 10)'", "Filter: keep only elements where .price > 10"),
            ("jq '.[] | select(.tags | contains([\"urgent\"]))'", "Filter: keep elements whose .tags array contains 'urgent'"),
            ("jq 'sort_by(.date) | reverse'", "Sort array by .date, then reverse order (or use sort_by(-.date))"),
            ("jq 'group_by(.category)'", "Group array elements by .category into sub-arrays"),
            ("jq 'unique_by(.id)'", "Deduplicate array by .id (first occurrence kept)"),
            ("jq '.[] | {name, price: .price_usd}'", "Transform: output objects with renamed/reshaped fields"),
            ("jq '[.name, .email] | @csv'", "Output as CSV line (also @tsv, @sh to shell-escape strings)"),
            ("jq -r '.[].name'", "Raw output: strip JSON quotes from strings (for use in shell pipelines)"),
            ("jq 'length'", "Count: array length, string length, or object key count depending on input"),
            ("jq 'keys' / 'keys_unsorted'", "List object keys (sorted / insertion order)"),
            ("jq 'has(\"key\")'", "Check if object has key: returns true or false"),
            ("jq 'if .score > 5 then \"high\" else \"low\" end'", "Conditional: if-then-else-end expression"),
            ("jq '.[] | .name // \"unknown\"'", "Default value: use \"unknown\" if .name is null or missing (// operator)"),
            ("jq 'del(.password, .secret)'", "Delete specified keys from each object"),
            ("jq -s 'add' file.json", "Slurp mode (-s): read entire array, then add all numbers / merge all objects"),
            ("jq -s '.[0] * .[1]' a.json b.json", "Slurp two files, then deep-merge first object into second"),
            ("curl -s api.example.com | jq '.data[] | .id'", "Classic curl + jq pipeline: fetch JSON API, extract IDs"),
            ("jq -c '.' file.json", "Compact output: one JSON object per line (line-delimited JSON / JSONL)"),
        ],
        "systemd": [
            ("systemctl status <unit>", "Show runtime status, PID, recent log lines of a unit"),
            ("systemctl start / stop / restart <unit>", "Start, stop, or restart a service immediately"),
            ("systemctl enable / disable <unit>", "Auto-start service at boot / disable auto-start"),
            ("systemctl enable --now <unit>", "Enable and start in one command"),
            ("systemctl mask / unmask <unit>", "Prevent a unit from being started manually or by deps / undo"),
            ("systemctl list-units", "List all loaded/active units (services, sockets, mounts, devices)"),
            ("systemctl list-units --state=failed", "Show only failed units (great for troubleshooting after reboot)"),
            ("systemctl list-unit-files", "List all installed unit files and their enable/disable state"),
            ("systemctl daemon-reload", "Reload systemd config after editing unit files (no restart needed)"),
            ("systemctl cat <unit>", "Print the unit file(s) of a service to the terminal"),
            ("systemctl edit <unit> --full", "Edit the full unit file (opens $EDITOR)"),
            ("systemctl show <unit>", "Dump all properties of a unit in key=value format"),
            ("journalctl -u <unit>", "Show logs for a specific unit"),
            ("journalctl -u <unit> -f", "Follow (tail -f) logs for a unit in real time"),
            ("journalctl -u <unit> --since today", "Logs since midnight; also --since '1 hour ago', --until '2026-05-30'"),
            ("journalctl -u <unit> -n 50", "Last 50 log lines; --no-pager to bypass less"),
            ("journalctl -xe", "Jump to end of journal, show extra context (-x) in pager (-e)"),
            ("journalctl --disk-usage", "Show how much disk space the journal is using"),
            ("journalctl --vacuum-time=7d", "Delete journal entries older than 7 days"),
            ("systemd-analyze", "Show how long the last boot took (kernel + initrd + userspace)"),
            ("systemd-analyze blame", "List services sorted by startup time (find boot bottlenecks)"),
            ("systemd-analyze critical-chain", "Tree view of time-critical chain of units at boot"),
            ("sudo systemctl reboot / poweroff", "Reboot or power off via systemd (polite; not magic SysRq)"),
            ("systemctl is-active / is-enabled <unit>", "Check if unit is running / enabled (returns exit code for scripts)"),
            ("systemctl kill -s SIGTERM <unit>", "Send a signal to all processes in a unit's cgroup"),
            ("systemctl list-timers", "Show all systemd timers (cron-like scheduled tasks) and their next run"),
        ],
        "tmux": [
            ("tmux new -s <name>", "Create a new session with a name (keeps it organised)"),
            ("tmux attach -t <name>", "Reattach to an existing named session"),
            ("tmux attach", "Reattach to the most recently used session"),
            ("tmux ls", "List all running sessions"),
            ("tmux kill-session -t <name>", "Kill a specific session"),
            ("tmux kill-server", "Kill the tmux server (destroys ALL sessions)"),
            ("Prefix = Ctrl+b (default)", "All tmux commands start with the prefix key"),
            ("Prefix + c", "Create a new window (tab) in the current session"),
            ("Prefix + ,", "Rename the current window"),
            ("Prefix + n / p / <number>", "Next window / previous window / jump to window by number"),
            ("Prefix + w", "Interactive window list: preview, search, and switch"),
            ("Prefix + &", "Kill current window (with confirmation)"),
            ("Prefix + %", "Split pane vertically (left/right)"),
            ("Prefix + \"", "Split pane horizontally (top/bottom)"),
            ("Prefix + arrow keys", "Navigate between panes (hold Prefix to repeat)"),
            ("Prefix + Ctrl+arrow", "Resize current pane by 1 cell in arrow direction"),
            ("Prefix + Alt+arrow", "Resize current pane by 5 cells in arrow direction"),
            ("Prefix + { / }", "Swap current pane with previous / next pane"),
            ("Prefix + z", "Zoom current pane to full window (toggle; same key to unzoom)"),
            ("Prefix + x", "Kill current pane (with confirmation)"),
            ("Prefix + !", "Break current pane out into its own window"),
            ("Prefix + d", "Detach from session (leave everything running in background)"),
            ("Prefix + [", "Enter copy/scroll mode: arrow keys, PgUp/PgDn, / search, q quit"),
            ("Prefix + ]", "Paste the most recently copied text from buffer"),
            ("Prefix + =", "Choose a paste buffer interactively"),
            ("Prefix + :", "Enter tmux command prompt (same commands as tmux.conf or shell)"),
            ("Prefix + ?", "List all key bindings with short descriptions"),
            ("Prefix + s", "Interactive session list: preview and switch sessions"),
            ("Prefix + $", "Rename current session"),
            ("set -g mouse on", "Enable mouse: click panes/windows, scroll in copy mode (put in ~/.tmux.conf)"),
            ("set -g history-limit 50000", "Increase scrollback buffer to 50k lines"),
            ("set -g @plugin 'tmux-plugins/tpm'", "Tmux Plugin Manager: install plugins declaratively"),
        ],
        "YAML": [
            ("key: value", "Basic key-value pair (colon + space required)"),
            ("name: John\nage: 30\nactive: true", "Simple mapping (dict): string, integer, boolean values"),
            ("items:\n  - apple\n  - banana\n  - cherry", "List (array): each item prefixed with dash + space, indented under key"),
            ("nested:\n  subkey:\n    deeper: value", "Nesting: use consistent indentation (2 or 4 spaces, never tabs!)"),
            ("---", "Document separator: start of a new YAML document in the same file/stream"),
            ("...", "Document end marker (optional; signals end without starting new document)"),
            ("# comment", "Comment: everything after # to end of line is ignored"),
            ("key: >\n  multi-line\n  string here", "Folded block scalar (>): newlines become spaces (wrapped text)"),
            ("key: |\n  line 1\n  line 2\n  line 3", "Literal block scalar (|): newlines preserved exactly (code/config)"),
            ("key: |-\n  line 1\n  line 2\n", "Literal with strip chomp (-): trailing newline removed"),
            ("name: &label John\nuser: *label", "Anchors and aliases: & defines a reference, * dereferences it (DRY)"),
            ("<<: *common", "Merge key: pull all keys from an aliased mapping into current mapping"),
            ("\"quoted string\" / 'single quoted'", "Quoting: double = escape sequences active, single = literal"),
            ("no: no / yes: yes", "Booleans: true/false, yes/no, on/off all valid (be explicit to avoid surprises)"),
            ("null-value: null / ~", "Null: null, ~, or just leave the value empty"),
            ("iso_date: 2026-05-31", "Dates: YYYY-MM-DD is auto-parsed as a date in most YAML libraries"),
            ("list-of-maps:\n  - name: a\n    val: 1\n  - name: b\n    val: 2", "List of objects: dash then keys indented on next line"),
            ("env: ${HOME}/config", "Environment variable interpolation (not standard; supported by docker-compose, Ansible)"),
            ("!custom_tag value", "Tags: type hints for custom parsing (!!str, !!int, !!timestamp are built-in)"),
            (">-  or  |+", "Block chomp indicators: - strips final newline, + keeps all trailing newlines"),
            ("image: nginx:latest\nports:\n  - \"80:80\"\nvolumes:\n  - ./app:/usr/share/nginx/html", "Classic docker-compose.yml pattern: service definition with ports and volumes"),
        ],
        "crontab": [
            ("* * * * * command", "Five-field schedule: minute hour day-of-month month day-of-week"),
            ("m h dom mon dow", "Field order: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-7, 0 and 7 = Sunday)"),
            ("0 2 * * * backup.sh", "Run at 2:00 AM every day (minute=0, hour=2)"),
            ("*/15 * * * * check.sh", "Every 15 minutes (*/step in any field)"),
            ("0 9 * * 1-5 report.sh", "9:00 AM Monday through Friday (1-5 = Mon-Fri)"),
            ("0 0 1 * * invoice.sh", "Midnight on the 1st of every month"),
            ("0 0 1 1 * yearly.sh", "Midnight on January 1st (first day of first month)"),
            ("0 */6 * * * task.sh", "Every 6 hours (at minute 0 of hour 0, 6, 12, 18)"),
            ("0 9,17 * * * twice.sh", "At 9:00 AM and 5:00 PM (comma-separated values)"),
            ("@reboot command", "Run once at system startup (non-standard but widely supported)"),
            ("@hourly / @daily / @weekly / @monthly", "Shortcuts: run hourly/daily/weekly/monthly (equivalent to 0 * * * *, 0 0 * * *, etc.)"),
            ("@yearly / @annually", "Run once a year (equivalent to 0 0 1 1 *)"),
            ("crontab -e", "Edit your user's crontab (opens $EDITOR)"),
            ("crontab -l", "List your current crontab entries"),
            ("crontab -l -u <user>", "List another user's crontab (requires sudo)"),
            ("crontab -r", "Remove (delete) your entire crontab (careful — no confirmation)"),
            ("crontab <file>", "Install a crontab from a file (replaces current one)"),
            ("MAILTO=user@example.com", "Email cron output to this address (set at top of crontab)"),
            ("0 3 * * * cmd > /dev/null 2>&1", "Silent cron: discard all output (no email, no log spam)"),
            ("0 3 * * * cmd >> /var/log/backup.log 2>&1", "Log cron output to a file for debugging"),
            ("SHELL=/bin/bash\nPATH=/usr/local/bin:/usr/bin", "Set environment at top of crontab (shell, PATH, MAILTO, HOME)"),
            ("*/5 * * * * flock -n /tmp/lock cmd", "Prevent overlapping runs: flock ensures only one instance at a time"),
        ],
        "ffmpeg": [
            ("ffmpeg -i input.mp4 output.avi", "Convert video format (ffmpeg detects codec from extension)"),
            ("ffmpeg -i input.mov -c copy output.mp4", "Remux: change container without re-encoding (fast, lossless; -c copy = copy codec)"),
            ("ffmpeg -i input.mp4 -c:v libx264 -crf 23 -preset medium out.mp4", "Re-encode H.264: CRF 0-51 (23=default, lower=better/larger), preset = speed vs size"),
            ("ffmpeg -i input.mp4 -c:v libx265 -crf 28 out.mp4", "Re-encode H.265/HEVC: ~50% smaller than H.264 at same quality, but slower"),
            ("ffmpeg -i input.mp4 -ss 00:01:30 -to 00:02:45 -c copy cut.mp4", "Trim without re-encoding: -ss start, -to end (seek to nearest keyframe with -c copy)"),
            ("ffmpeg -i input.mp4 -ss 00:01:30 -t 30 -c copy clip.mp4", "Extract 30 seconds starting at 1:30 (-t = duration, alternative to -to)"),
            ("ffmpeg -i input.mp4 -vf scale=1280:720 out.mp4", "Resize video to 1280x720 (scale=iw/2:-1 = half width, auto height)"),
            ("ffmpeg -i input.mp4 -vf fps=30 out.mp4", "Change frame rate to 30 fps"),
            ("ffmpeg -i video.mp4 -i audio.m4a -c copy merged.mp4", "Mux video and audio from separate files into one container"),
            ("ffmpeg -i input.mp4 -vn -c:a libmp3lame -q:a 2 audio.mp3", "Extract audio only: -vn = no video, VBR quality 0-9 (0=best, 2 is good)"),
            ("ffmpeg -i input.mp4 -an -c:v copy video_only.mp4", "Strip audio: -an = no audio, keep video stream as-is"),
            ("ffmpeg -i input.mp4 -af \"volume=2.0\" louder.mp4", "Double audio volume (volume=0.5 = half, volume=10dB)"),
            ("ffmpeg -i input.mp4 -vf \"rotate=PI/2\" rotated.mp4", "Rotate video 90 degrees clockwise (use -PI/2 for counter-clockwise)"),
            ("ffmpeg -i input.mp4 -vf \"crop=w:h:x:y\" cropped.mp4", "Crop: w=width, h=height, x/y = top-left corner offset"),
            ("ffmpeg -i input.mp4 -vf \"drawtext=text='hello':x=10:y=10:fontsize=24:fontcolor=white\" out.mp4", "Overlay text on video"),
            ("ffmpeg -i input.gif -movflags faststart -pix_fmt yuv420p out.mp4", "Convert animated GIF to MP4 (web-optimised with faststart)"),
            ("ffmpeg -i input.mp4 -vf fps=10,scale=320:-1 out.gif", "Convert video to animated GIF (limit fps and resolution to keep size down)"),
            ("ffmpeg -i input.mp4 -frames:v 1 screenshot.jpg", "Extract first frame as still image (-ss 00:05 to take screenshot at 5s)"),
            ("ffmpeg -i input.mp4 -filter_complex \"[0:v]trim=start=10:end=20,setpts=PTS-STARTPTS[v]\" -map [v] out.mp4", "Trim with frame-accurate precision via filter_complex (re-encodes)"),
            ("ffmpeg -loop 1 -i bg.jpg -i audio.mp3 -c:v libx264 -tune stillimage -shortest out.mp4", "Create video from image + audio: loop image for duration of audio"),
            ("ffmpeg -f concat -i files.txt -c copy combined.mp4", "Concatenate videos: files.txt lists 'file input1.mp4', 'file input2.mp4', etc."),
            ("ffprobe -v quiet -print_format json -show_format -show_streams input.mp4", "Inspect media file: codec, resolution, bitrate, duration, streams (JSON output)"),
        ],
        "networking": [
            ("ping -c 4 <host>", "Send 4 ICMP echo requests; check if host is reachable and measure RTT"),
            ("ping -i 0.2 <host>", "Flood ping: send every 0.2s (default 1s; requires root for <0.2s)"),
            ("ip addr show", "List all network interfaces with IP addresses, state, and MAC"),
            ("ip route show", "Show routing table (default gateway, subnets, interfaces)"),
            ("ip neigh", "Show ARP table: IP-to-MAC address mappings on the local network"),
            ("ip -s link", "Show interface statistics: RX/TX bytes, packets, errors, drops"),
            ("ss -tlnp", "List listening TCP sockets with process names (-u for UDP, -a for all)"),
            ("ss -s", "Summary: total sockets by state (ESTAB, LISTEN, CLOSE-WAIT, etc.)"),
            ("ss -t state established dst :443", "Filter: established TCP connections to port 443"),
            ("dig example.com", "DNS lookup: returns A/AAAA records, name servers, and query time"),
            ("dig +short example.com", "Short output: just the IP address(es), no metadata"),
            ("dig -x 8.8.8.8", "Reverse DNS lookup: IP address to hostname"),
            ("dig example.com MX", "Query specific record type: MX, NS, TXT, SOA, CNAME, ANY"),
            ("dig @1.1.1.1 example.com", "Query a specific DNS resolver instead of the system default"),
            ("host example.com", "Simple DNS lookup (more concise than dig for quick checks)"),
            ("nslookup example.com", "Interactive or one-shot DNS query (older, but still everywhere)"),
            ("tcpdump -i eth0 -n port 443", "Capture packets on eth0, don't resolve names (-n), filter port 443"),
            ("tcpdump -i any -w capture.pcap host 10.0.0.5", "Capture all traffic to/from 10.0.0.5 on any interface, write to pcap file"),
            ("tcpdump -r capture.pcap -n | head", "Read a saved pcap file and display first packets"),
            ("nmap -sV <host>", "Service/version detection: probe open ports to identify what's running"),
            ("nmap -p 1-1000 <host>", "Scan specific port range; -p- = all 65535 ports"),
            ("nmap -sC <host>", "Run default NSE scripts (safe, useful: service info, HTTP title, SSH host key)"),
            ("nmap -sn 192.168.1.0/24", "Ping sweep: discover which hosts are up on a subnet (no port scan)"),
            ("mtr <host>", "My Traceroute: combines ping + traceroute with live-updating stats"),
            ("nc -lvp 4444", "Netcat listen: TCP server on port 4444 (-l listen, -v verbose, -p port)"),
            ("nc <host> <port>", "Netcat connect: raw TCP client; type/paste data or pipe stdin"),
            ("nc -zv <host> 22-80", "Port scan with netcat: check which ports are open (-z = scan, -v = verbose)"),
            ("iperf3 -s / iperf3 -c <host>", "Bandwidth benchmark: run server on one machine, client on another"),
            ("iperf3 -c <host> -u -b 100M", "UDP test at 100 Mbps (measure jitter and packet loss, not just TCP throughput)"),
        ],
        "npm / Node Tooling": [
            ("npm init / npm init -y", "Create package.json interactively / with defaults (skip prompts)"),
            ("npm install / npm i", "Install all dependencies listed in package.json (node_modules + lock file)"),
            ("npm install <pkg> / npm i <pkg>", "Install a package and add to dependencies (--save is default since npm 5)"),
            ("npm install -D <pkg> / npm i -D <pkg>", "Install as devDependency (--save-dev: tests, linters, build tools)"),
            ("npm install -g <pkg>", "Install globally (CLI tools: nodemon, serve, typescript, eslint)"),
            ("npm uninstall <pkg>", "Remove a package from node_modules and package.json"),
            ("npm update", "Update all packages to latest versions within semver range in package.json"),
            ("npm outdated", "List packages that have newer versions available (current vs wanted vs latest)"),
            ("npm audit / npm audit fix", "Check for known vulnerabilities in dependencies / auto-fix safe ones"),
            ("npm ls / npm ls <pkg>", "List installed packages as a tree (--depth=0 for top-level only)"),
            ("npm run <script>", "Run a script defined in package.json scripts block (test, build, start, dev)"),
            ("npm run <script> -- --flag", "Pass arguments through to the underlying command (-- separates npm args from script args)"),
            ("npm exec / npx <pkg>", "Run a package binary: installs temporarily if not present, runs, then cleans up"),
            ("npx create-react-app my-app", "Scaffold a project with a generator package without installing it globally"),
            ("npm ci", "Clean install: deletes node_modules, installs exact versions from lock file (for CI/CD)"),
            ("npm cache clean --force", "Clear npm cache (when installs are corrupt or disk space is tight)"),
            ("npm version patch / minor / major", "Bump version in package.json and create a git tag (1.0.0 -> 1.0.1 / 1.1.0 / 2.0.0)"),
            ("npm publish", "Publish package to the npm registry (cd into package dir, ensure version is bumped)"),
            ("nvm install 22 / nvm use 22", "Install and switch to Node.js v22 (nvm is a separate install: github.com/nvm-sh/nvm)"),
            ("node --inspect-brk app.js", "Start Node.js with debugger paused on first line (attach Chrome DevTools on chrome://inspect)"),
            ("node -e \"console.log(process.env.PATH)\"", "Evaluate inline JavaScript from the command line (-e = eval, no file needed)"),
            ("node -p \"fs.readdirSync('.')\"", "Evaluate and print the result (-p = print, good for one-liners that return a value)"),
            ("node --require ./instrument.js app.js", "Preload a module before the app starts (--require/-r; useful for instrumentation)"),
            ("process.env.NODE_ENV = 'production'", "Set runtime environment; most frameworks check this (development/production/test)"),
            ("npm search <keyword>", "Search the npm registry for packages (or browse npmjs.com)"),
            ("npm doctor", "Diagnose npm install: check registry connectivity, git, cache, permissions"),
        ],
        "Textual": [
            # --- CLI ---
            ("textual run app.py", "Run a Textual app (auto-detects App subclass)"),
            ("textual run --dev app.py", "Dev mode: live CSS reload, interactive console with ctrl+c"),
            ("textual console", "Open Textual console in browser to inspect messages, DOM, logs"),
            ("textual diagnose", "Print system info for bug reports: Python version, terminal, platform"),
            ("textual build app.py", "Package a Textual app as a standalone executable (pyinstaller-based)"),
            ("textual keys", "Key reference: show all key names usable in BINDINGS"),
            ("textual colors", "Color reference: show all named colors available in CSS"),
            ("textual borders", "Border styles showcase: all border types with examples"),
            ("textual easing", "Easing curves showcase: animation timing functions"),
            ("ctrl+c (in dev mode)", "Drop into Textual console without killing the app"),
            # --- Core patterns ---
            ("class MyApp(App):", "App = top-level application; holds screens, manages modes"),
            ("def compose(self) -> ComposeResult:", "Declare initial widget tree with yield; runs once on mount"),
            ("def on_mount(self) -> None:", "Post-mount setup: populate DataTables, load data, set initial state"),
            ("self.query_one('#id', WidgetClass)", "Get exactly one widget by CSS selector + type; raises if missing/duplicate"),
            ("self.query('#id', WidgetClass)", "Get list of matching widgets (can be zero, one, or many)"),
            ("self.notify('msg', severity='info')", "Show toast notification: info, warning, error levels"),
            ("self.app.push_screen(MyModal(), callback)", "Push a new Screen onto the stack; optional callback receives dismiss value"),
            ("self.dismiss(value)", "Pop current screen from stack; passes value to push_screen callback"),
            # --- Reactive attributes ---
            ("reactive = reactive(0)", "Declare reactive class attribute; re-renders widget on change"),
            ("def watch_reactive(self, old, new):", "Called automatically when reactive changes value"),
            ("def compute_reactive(self):", "Computed reactive: auto-calculated from other reactives"),
            ("self.reactive = 42  # triggers watch", "Setting a reactive attribute fires the watcher + refresh"),
            # --- BINDINGS ---
            ("BINDINGS = [Binding('n', 'add', 'New Item')]", "Declare key bindings: key, action name, display text"),
            ("def action_add(self) -> None:", "Action handler: 'add' binding calls this method"),
            ("Binding('ctrl+q', 'quit', 'Quit', priority=True)", "Priority bindings take precedence over focused widget bindings"),
            # --- Containers / Layout ---
            ("Vertical(*children) / Horizontal(*children)", "Stack widgets vertically or horizontally"),
            ("Grid(*children)", "CSS Grid container: position children with row-span/column-span in TCSS"),
            ("Container(*children)", "Generic container for grouping and CSS targeting"),
            ("VerticalScroll(*children)", "Vertical container with built-in scrollbar (no need for overflow CSS)"),
            ("HorizontalScroll(*children)", "Horizontal container with built-in scrollbar"),
            ("id='my_container'", "Set widget id (CSS target: #my_container, query_one target)"),
            ("classes='card highlight'", "Add CSS classes (space-separated; CSS target: .card, .highlight)"),
            # --- Built-in Widgets ---
            ("Label(text, id=...)", "Simple static or updatable text; update with label.update('new')"),
            ("Static(text, id=...)", "Renders text with optional markup; use for multi-line read-only blocks"),
            ("Button(label, variant='primary', id=...)", "Clickable button; variants: primary, default, warning, error"),
            ("Input(placeholder='...', password=False, id=...)", "Single-line text input; password=True masks characters"),
            ("TextArea(language='python', id=...)", "Multi-line text editor with syntax highlighting (Tree-sitter)"),
            ("DataTable(id=...)", "Cursor-navigable table: add_columns(), add_row(), cursor_type='row'"),
            ("ListView(*ListItem(Label(...)))", "Vertical selection list: arrow keys navigate, Enter selects"),
            ("ListItem(*child_widgets, name=...)", "Item inside a ListView; name attribute for storing IDs"),
            ("Select(options, prompt='...', id=...)", "Dropdown select: list of (label, value) tuples"),
            ("Switch(value=True, id=...)", "Toggle on/off switch widget"),
            ("Checkbox(label, value=False, id=...)", "Checkbox with label"),
            ("RadioSet(*RadioButton(...))", "Group of mutually exclusive radio buttons"),
            ("ProgressBar(total=100, show_eta=True, id=...)", "Progress bar with optional percentage and ETA"),
            ("Header() / Footer()", "Built-in header (clock + title) and footer (key bindings display)"),
            ("TabbedContent(*TabPane(...))", "Tab container: each TabPane is one tab's content"),
            ("TabPane(title, id=...)", "Single tab inside TabbedContent; title shown on tab label"),
            ("Tabs(*Tab(...))", "Alternative tab system: lighter weight, manual content switching"),
            ("Tab(label, id=...)", "Individual tab for Tabs widget (not TabbedContent)"),
            ("RichLog(id=..., highlight=True, markup=True)", "Scrollable log with syntax highlighting; .write() to append"),
            ("Markdown(markdown_string, id=...)", "Render Markdown: headings, code blocks, tables, links"),
            ("Tree(label, id=...)", "Tree widget: root.add_leaf() / root.add() to build hierarchy"),
            ("DirectoryTree(path, id=...)", "Lazy-loaded filesystem tree browser; expands on demand"),
            ("Placeholder(label, id=...)", "Wireframe placeholder for layout prototyping (dev tool)"),
            ("ContentSwitcher(*children, initial=...)", "Show one child at a time; programmatically switch visible child"),
            ("LoadingIndicator(id=...)", "Spinning animation: show while a task is in progress"),
            ("Rule(line_style='heavy', id=...)", "Horizontal rule/divider: heavy, solid, dashed, double, etc."),
            ("Sparkline(data, id=...)", "Mini inline chart: display a trend as a text-based sparkline"),
            ("Digit(id=...)", "Single-digit display with themed styling for clocks/counters"),
            ("Collapsible(title=...)", "Expand/collapse container with a clickable title"),
            ("OptionList(*options, id=...)", "Selectable option list: each option can have an ID and disabled state"),
            # --- CSS / TCSS ---
            ("DEFAULT_CSS = open('style.tcss').read()", "Load CSS from a file in a Widget or App"),
            ("CSS_PATH = ['a.tcss', 'b.tcss']", "App-level CSS paths: each file is loaded and watched in dev mode"),
            ("#widget_id { ... }", "CSS selector: target by widget id (use the id you pass to constructor)"),
            (".class_name { ... }", "CSS selector: target by class (add with classes='class_name')"),
            ("WidgetName { ... }", "CSS selector: target all instances of a widget type by class name"),
            ("$accent, $surface, $boost, $primary, $error, $text, $background", "Built-in CSS color variables (from the current theme)"),
            ("text-style: bold italic;", "Typography: bold, italic, underline, strike, reverse, dim"),
            ("color: $accent; / background: $surface;", "Text color and background color"),
            ("height: 1fr; width: 100%;", "fr = fraction of available space; % = percentage of parent"),
            ("align: center middle;", "Align children inside a container: horizontal vertical"),
            ("overflow: auto | hidden | scroll;", "Scroll behavior for content exceeding the widget bounds"),
            # --- Screens ---
            ("class MyScreen(Screen):", "Full-screen view: compose widgets, handle key events"),
            ("class MyModal(ModalScreen):", "Modal screen: dims background, blocks interaction below, Escape to dismiss"),
            ("with PreventDefault():", "Context manager inside Screen: swallow a key event so parent screens ignore it"),
            # --- Messages / Events ---
            ("def on_button_pressed(self, event):", "Handler for Button.Pressed message (event.button = which button)"),
            ("def on_input_changed(self, event):", "Handler for Input.Changed (event.value = new text, event.input = widget)"),
            ("def on_data_table_row_selected(self, event):", "Handler for DataTable row selection (event.row_key = selected row key)"),
            ("def on_list_view_selected(self, event):", "Handler for ListView selection (Enter/click)"),
            ("def on_list_view_highlighted(self, event):", "Handler for ListView highlight change (arrow key navigation)"),
            ("def on_key(self, event):", "Raw key handler: event.key gives key name (also .character, .is_printable)"),
            ("BINDINGS = [Binding('x', 'foo', 'Foo')]; action_foo()", "Bind key to action: Binding triggers action_foo() or can be overridden in a parent"),
        ],
    }

    for title in sheets:
        conn.execute(
            "INSERT INTO sheets (title) VALUES (?)",
            (title,),
        )
        sheet_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]
        for term, definition in entries.get(title, []):
            conn.execute(
                "INSERT INTO entries (sheet_id, term, definition) VALUES (?, ?, ?)",
                (sheet_id, term, definition),
            )

    conn.commit()
