from .base_converter.base_converter import BaseConverterTab
from .budget.budget import BudgetTab
from .calorie_budgeter.calorie_budgeter import CalorieBudgeterTab
from .changelog.changelog import ChangelogTab
from .cheats.cheats import CheatSheetTab
from .clock.clock import ClockTab
from .color_picker.color_picker import ColorPickerTab
from .countdown.countdown import CountdownTab
from .csv_viewer.csv_viewer import CsvViewerTab
from .games.games_tab import GamesTab
from .gitignore_builder.gitignore_builder import GitignoreBuilderTab
from .habits.habits import HabitTab
from .job_tracker.job_tracker import JobTrackerTab
from .json_tool.json_tool import JsonToolTab
from .lorem.lorem import LoremTab
from .money.money import MoneyTab
from .music.music_tab import MusicTab
from .noting.noting import NoteTakingTab
from .port_checker.port_checker import PortCheckerTab
from .qr_extractor.qr_extractor import QRToolTab
from .random_picker.random_picker import RandomPickerTab
from .recipes.recipes import RecipesTab
from .regex_tester.regex_tester import RegexTesterTab
from .subnet_calc.subnet_calc import SubnetCalcTab
from .timezones.timezones import TimeZoneTab
from .todos.todos import TodoTab
from .typing_test.typing_test import TypingTestTab
from .unit_converter.unit_converter import UnitConverterTab
from .word_counter.word_counter import WordCounterTab
